### ISSUE TITLE
Сжатые изображения [0.9.20.c375f89]

### ISSUE THREAD

**Issue by uunium** [y2k/JoyReactor#21]
При открытии поста не прогружаются изображения, а выглядят как сжатые. Лог файл в принципе тот же, плюс скриншот.
Nexus 7 (2013), 5.1.1.
[back.txt](https://github.com/y2k/JoyReactor/files/120209/back.txt)
![screenshot_2016-02-06-11-37-33](https://cloud.githubusercontent.com/assets/5246118/12865990/c018b1b4-ccc6-11e5-89dc-188ed4a44aa0.png)

**Comment by uunium** [comment]
И еще одно, изображения новых постов прогружаются довольно таки медленно (с интернетом всё впорядке), например при переходе в разные теги, ранее не посещенные.

**Comment by y2k** [comment]
Пофиксил "сжатые изображения".
Проблема была с сервере кеширующим картинки https://github.com/y2k/RemoteCache

> прогружаются довольно таки медленно

Картинки сначала выгружаются на сторонний сервер (см выше) тк joyreactor.cc не поддерживает ресайзинг - соответвенно появлятся задержка (если этой картинки раньше не было).

Можно ли с этим что-то сделать, большой вопрос.
Если критично, можно создать отдельную таску (но вряд ли в ближайшее время по ней будет прогресс).
